spin_version = "1"
authors = ["patterns <addq1eax@gmail.com>"]
description = "Pink Elephants on Parade"
name = "cloud_start"
trigger = { type = "http", base = "/" }
version = "0.6.8"

[variables]
self_actor = { default = "echo" }
site_name = { required = true }
domain_base = { required = true }
redis_server = { required = true }
redis_login = { required = true, secret = true }
verifier_proxy = { required = true }
verifier_bearer = { required = true, secret = true }
httpsig_origin = { default = "" }
httpsig_gateway = { default = "" }

[[component]]
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*", "shortcodes/*", "themes/bromide/templates/*", "themes/bromide/scripts/*" ]
[component.source]
url = "https://github.com/fermyon/bartholomew/releases/download/v0.9.0/bartholomew.wasm"
digest = "sha256:c7261135e5e8057c0f4646efd0df2145109e60b7c1911726c3655abf58e846a9"
[component.trigger]
route = "/..."

[[component]]
id = "fileserver"
files = [{ source = "themes/bromide/static", destination = "/" }, { source = "static/", destination = "/" } ]
[component.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm"
digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4"
[component.trigger]
route = "/static/..."

[[component]]
id = "inbox"
source = "modules/inbox.wasm"
allowed_http_hosts = ["verifier-key-rcv.pages.dev"]
[component.trigger]
route = "/inbox"
[component.config]
redis_address = "redis://{{ redis_login }}@{{ redis_server }}"
verifier_proxy_uri = "https://{{ verifier_proxy }}/api/verifiers"
verifier_proxy_bearer = "{{ verifier_bearer }}"
httpsig_host_origin = "{{ httpsig_origin }}"
httpsig_host_gateway = "{{ httpsig_gateway }}"

[[component]]
id = "outbox"
source = "modules/outbox.wasm"
allowed_http_hosts = ["verifier-key-rcv.pages.dev"]
[component.trigger]
route = "/outbox"
[component.config]
redis_address = "redis://{{ redis_login }}@{{ redis_server }}"
verifier_proxy_uri = "https://{{ verifier_proxy }}/api/verifiers"
verifier_proxy_bearer = "{{ verifier_bearer }}"
httpsig_host_origin = "{{ httpsig_origin }}"
httpsig_host_gateway = "{{ httpsig_gateway }}"

[[component]]
id = "webfinger"
source = "modules/webfinger.wasm"
[component.trigger]
route = "/well-known/webfinger"
[component.config]
site_name = "{{ site_name }}"
site_subdomain = "{{ site_name }}.{{ domain_base }}"
self_actor = "{{ self_actor }}"
[[component]]
id = "dotwebfinger"
source = "modules/webfinger.wasm"
[component.trigger]
route = "/.well-known/webfinger"
[component.config]
site_name = "{{ site_name }}"
site_subdomain = "{{ site_name }}.{{ domain_base }}"
self_actor = "{{ self_actor }}"

[[component]]
id = "actor"
source = "modules/actor.wasm"
[component.trigger]
route = "/u/..."
[component.config]
site_subdomain = "{{ site_name }}.{{ domain_base }}"
self_actor = "{{ self_actor }}"

