name: build-test

env:
  ZIG_VERSION: 0.11.0-dev.3000+d71a43ec2

on:
  pull_request:
    branches:
      - main

    paths:
      - "src/**/*.zig"
      - "src/*.zig"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    name: build test
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install zig
        run: |
          curl https://ziglang.org/builds/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          sudo tar -C /usr/local -xf zig.tar.xz
          rm zig.tar.xz

      - name: test module link
        run: zig build

