name: Deploy
env:
  ZIG_VERSION: 0.12.0-dev.1814+5c0d58b71
  OCI_NAMESPC: patterns/pink-elephants:latest

on:
  push:
    branches:
      - main

jobs:
  spin:
    name: Build against zig-0.12.0
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fetch zig-0.12.0
        run: |
          curl https://ziglang.org/builds/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          sudo tar -C /usr/local -xf zig.tar.xz
          sudo ln -s /usr/local/zig-linux-x86_64-${{env.ZIG_VERSION}}/zig /usr/local/bin/zig
          rm zig.tar.xz

      - name: Check tests
        run: zig build test

      - name: Build components
        run: |
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSmall
          mv ./zig-out/bin ./bartholomew/modules

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1


      - name: Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | spin registry login ghcr.io --username ${{ github.actor }} --password-stdin 
          cd ./bartholomew && spin registry push ghcr.io/${{ env.OCI_NAMESPC }}

