name: nightly
env:
  ZIG_VERSION: 0.12.0-dev.1303+8f4853369

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  nightly:
    name: Build against zig-0.12.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch zig-0.12.0
        run: |
          curl https://ziglang.org/builds/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          sudo tar -C /usr/local -xf zig.tar.xz
          sudo ln -s /usr/local/zig-linux-x86_64-${{env.ZIG_VERSION}}/zig /usr/local/bin/zig
          rm zig.tar.xz

      - name: Check tests
        run: zig build test

      - name: Build components
        run: zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSmall

      - name: Save wasm binary
        uses: actions/upload-artifact@v3
        with:
          name: wasm-bin
          path: zig-out

